CAPS_WORD_ENABLE = yes
TAP_DANCE_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes

# size optimizations
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
GRAVE_ESC_ENABLE = no
BOOTMAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
